name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/final_be-node-app:latest .

    - name: Push image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/final_be-node-app:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 3.25.83.75 >> ~/.ssh/known_hosts
        echo "$SSH_PRIVATE_KEY" > id_rsa
        chmod 600 id_rsa
        ssh -i id_rsa ubuntu@3.25.83.75 << 'EOF'
          docker stop final_be-node-app
          docker rm final_be-node-app
          docker rmi ${{ secrets.DOCKER_USERNAME }}/final_be-node-app:latest
          docker-compose up -d
        EOF
        rm id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


    
